# Generated by Django 5.1.6 on 2025-02-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="prazo_final_tarefa",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
