# Generated by Django 5.1.6 on 2025-02-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0002_alter_tarefa_prazo_final_tarefa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="prazo_inicial_tarefa",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
