# Generated by Django 5.1.6 on 2025-03-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_tarefa_prazo_inicial_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='deletada',
            field=models.BooleanField(default=False),
        ),
    ]
