# Generated by Django 5.1.6 on 2025-03-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_foto_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto_funcionario',
            field=models.ImageField(upload_to='funcionariosnord'),
        ),
    ]
