# Generated by Django 5.1.6 on 2025-03-09 06:35

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_alter_funcionario_foto_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto_funcionario',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='funcionariosnord'),
        ),
    ]
